#!/bin/zsh
cd ~/Knotel/scd; source ~/.zshrc; git checkout master; 
conda activate scd; ipython __main__.py; conda deactivate
if [ -s ~/tmp/.scd/data.change ]
then
	cat ~/tmp/.scd/data.change | mail -s "$(date +%d-%m-%y-%H-%M-%S)"\
		$(cat ~/.scd/mail)
fi
mv ~/tmp/.scd/data.change ~/.scd/logs/RAW/$(date +%d-%m-%y-%H-%M-%S).data.change
