version: 2

sources:
        - name: {{ TABLE_SCHEMA }}_{{ TABLE_CATALOG }}
          database: {{ TABLE_CATALOG }}
          schema: {{ TABLE_SCHEMA }}
          quoting:
                database: true
                schema: true
                identifier: true
          tables: 
          {% for __table__ in TABLES.keys() -%}
                - name: {{ __table__ }}
          {% endfor %}
         
models:
{% for __table__ in TABLES.keys() %}
- name: {{ TABLE_SCHEMA }}_{{ __table__ }}
  {% for __column__ in TABLES[__table__]['COLUMN_NAME'] if 'ID' in __column__ -%}
  {% if loop.first %}columns:{% endif %}
  - name: {{ TABLE_SCHEMA | lower }}__{{ __table__ | lower }}__{{ __column__ | lower }}
    tests:
    - not_null  
  {% endfor %}
{% endfor %}
